# Database 사용 여부
# Database type: Yaml, MySQL, MariaDB, PostgreSQL, SQLite, MongoDB
# yaml의 경우 players.yml 파일로 적용되며, mongodb의 경우 table에 collection 이름을 작성

database:
  type: "yaml"
  address: "localhost"
  port: "3306"
  database_name: ""
  table: "CashMF"
  username: ""
  password: ""