# Database 사용 여부
# Database type: Yaml, MySQL, MariaDB, PostgreSQL, SQLite

database:
  type: "yaml"
  address: "localhost"
  port: "3306"
  database_name: ""
  table: "CashAPI"
  username: ""
  password: ""
