name: CashMF
version: '0.0.1'
main: net.teamuni.cashmf.CashMF
api-version: 1.18
commands:
  캐시:
    usage: /<command>
    permission: cashmf.cash
permissions:
  cashmf.cash:
    default: true
  cashmf.help:
    default: true
  cashmf.look:
    default: true
  cashmf.pay:
    default: true
  cashmf.add:
    default: op
  cashmf.sub:
    default: op
