name: CashAPI
version: '${version}'
main: net.teamuni.cashmf.CashMF
api-version: 1.19
softdepend:
  - PlaceholderAPI
libraries:
  - com.zaxxer:HikariCP:5.0.1
commands:
  캐시:
    permission: cashapi.cash
permissions:
  cashapi.cash:
    default: true
  cashapi.look:
    default: true
  cashapi.help:
    default: true
  cashapi.add:
    default: op
  cashapi.sub:
    default: op